### ISSUE TITLE
Floating Point Issue When Converting kg to t

### ISSUE THREAD

**Issue by WarLord211** [mike-koch/ets2-mobile-route-advisor#107]
Its me again. The first issue dont show up, because github thought i was a spam bot?! 
Now it should work :)

I changed the weight to tonns (also i change the language to german) and by some trailers it shows up to 16 decimal Places like:

15,3450000005 t

or like in the screenshot
![zwischenablage01](https://cloud.githubusercontent.com/assets/10798954/14588346/91f789e8-04c7-11e6-9477-ad61d3866973.jpg)

is there a way to round this to two decimal places?

**Comment by mike-koch** [comment]
Well, this is the first time I have encountered GitHub blocking an issue due to a suspected "spam bot" :laughing:.  It looks like the original issue (#103) reappeared, but thanks for opening another issue along with a screenshot :smile: .  This is definitely an issue and can be easily fixed.  How many decimal places are shown in-game?  Or are there no decimal places shown at all?

**Comment by WarLord211** [comment]
in-game there are no decimal places.

i think 1 or 2 would be good.

**Comment by mike-koch** [comment]
This has been fixed for version 3.3.0.
